language: ruby


before_install:
- gem install bundler


before_script:
- mysql -e "create database IF NOT EXISTS myapp_dev;" -uroot

- mysql -e "create database IF NOT EXISTS myapp_test;" -uroot

- mysql -e "create database IF NOT EXISTS myapp_prod;" -uroot



rvm:
  - 2.2.0


env:
  - DB=mysql


script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
