development:
  adapter: mysql2
  database: myapp_dev
  username: travis
  encoding: utf8

test:
  adapter: mysql2
  database: myapp_test
  username: travis
  encoding: utf8


production:
  adapter: mysql2
  database: myapp_prod
  username: travis
  encoding: utf8
