development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: schooldb_dev
  pool: 5
  username: root
  password: root
  shost: localhost
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: schooldb_stage
  pool: 5
  username: root
  password: root
  shost: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: schooldb_prod
  pool: 5
  username: root
  password: root
  shost: localhost

